/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://tk7djmsxanbnpb26lqhb2cze5q.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-xogegzj6nfcr3kccxuwf3bjabu",
    "aws_cognito_identity_pool_id": "us-east-1:072edcb9-c43e-4bc9-897f-2b4d2dbab35c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_cOmrsPC8X",
    "aws_user_pools_web_client_id": "2cncehplsn9eugh6kjsuq3n3ae",
    "oauth": {},
    "aws_user_files_s3_bucket": "postagramc5173a9d5fdd4797899e3f1298153594145942-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
